---
- hosts:        kube-master[0]
  become:       yes
  gather_facts: no
  tasks:
  - name:   "pip | install openshift requirement"
    pip:
      name: openshift
  - name:   "create namespace"
    k8s:
      name:         meth
      api_version:  v1
      kind:         Namespace
      state:        present
  - name:   "create backend service"
    k8s:
      state:  present
      definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: cc-backend-service
            namespace:  meth
            labels:
              app:  nginx
              layer:  backend
          spec:
            selector:
              app:  nginx
              layer:  backend
            ports:
            - port: 80
              targetPort: 80
              name: nginx-http-backend
  - name:   "create backend deployment"
    k8s:
      state:  present
      definition:
        apiVersion: apps/v1
        kind:       Deployment
        metadata:
          name: nginx-backend
          namespace:  meth
          labels:
            app:  nginx
            layer:  backend
        spec:
          replicas: 3
          selector:
            matchLabels:
              app:  nginx
              layer:  backend
          template:
            metadata:
              labels:
                app:  nginx
                layer:  backend
            spec:
              containers:
              - name: nginx-backend
                image:  aweltzien/mocc-nginx-backend:1
                ports:
                - containerPort:  80
  - name:   "create frontend service"
    k8s:
      state:  present
      definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: cc-frontend-service
            namespace:  meth
            labels:
              app:  nginx
              layer:  frontend
          spec:
            type: NodePort
            selector:
              app:  nginx
              layer:  frontend
            ports:
            - port: 80
              targetPort: 80
              name: nginx-http-frontend
  - name:   "create frontend deployment"
    k8s:
      state:  present
      definition:
        apiVersion: apps/v1
        kind:       Deployment
        metadata:
          name: nginx-frontend
          namespace:  meth
          labels:
            app:  nginx
            layer:  frontend
        spec:
          replicas: 3
          selector:
            matchLabels:
              app:  nginx
              layer:  frontend
          template:
            metadata:
              labels:
                app:  nginx
                layer:  frontend
            spec:
              containers:
              - name: nginx-frontend
                image:  aweltzien/mocc-nginx-frontend:1
                ports:
                - containerPort:  80
